[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build]
cmds = ["./gradlew build -x test -x check --no-daemon"]

[phases.start]
cmd = "java -Dspring.profiles.active=prod -jar build/libs/WriteBuddy-0.0.1-SNAPSHOT.jar"

[variables]
JAVA_HOME = "/nix/store/*-openjdk-17*/lib/openjdk"